---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
    department: frontend-department
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      department: frontend-department
  template:
    metadata:
      labels:
        app: frontend
        department: frontend-department
    spec:
      containers:
      - name: frontend
        image: gcr.io/eshka-318719/frontend
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: frontend
    department: frontend-department
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http-80