[package]
name = "lab_4"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "0.5.1"
tabled = "0.2.2"
rand = "0.8.4"